AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CreatePermission:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: CreatePermission/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
  DeletePermission:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: DeletePermission/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
  GetAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: GetAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
  UpdateAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: UpdateAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active