AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  CreateAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: CreateAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - Ref: DependencyLayer
  DeleteAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: DeleteAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - Ref: DependencyLayer
  GetAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: GetAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - Ref: DependencyLayer
  UpdateAuth:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: UpdateAuth/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Policies:
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - Ref: DependencyLayer    
  CreatePermissions:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: CreatePermissions/index.handler
      Runtime: nodejs12.x
      Description: ''
      MemorySize: 128
      Timeout: 15
      Layers:
        - Ref: DependencyLayer
  DependencyLayer:
    Type: 'AWS::Serverless::LayerVersion'
    Properties:
      LayerName: auth-service-dependencies
      Description: 'Dependencies for auth service'
      ContentUri: dependencies/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: MIT
      RetentionPolicy: Retain
